### PR TITLE
step3: set debt ceilings

### PR DESCRIPTION
**Pull request by asymmetric**
This sets the debt ceilings for the collaterals defined in `step-3.json` to 0.

Collateral deployment is not implemented yet.

### CODE REVIEW

**Comment by gbalabasquer** [comment]
Hmm not getting why to 0.
As far as I understand you need to take care of preparing the spell for setting up the debt ceilings. Step 3 will leave that spell ready to be used.

**Comment by gbalabasquer** [comment]
As I understand it, the step 3 will not do more than deploying the spell.

**Comment by asymmetric** [comment]
It's in [the doc](https://docs.google.com/document/d/1Q3dIUvoLhv1icQ1umykzJT1_d3uOY_ZfTooyrszX_Zs/edit#), milestone 2 step 3:

> 3. MCD system is deployed with debt ceilings = 0 and the following collateral types (+ ETH)
> 4. Executive vote to set the debt ceilings to their actual values

So I thought to separate these two phases in the script as well.

**Comment by gbalabasquer** [comment]
hmm but the collateral types are already deployed with debt ceiling zero. The only thing to do in this step is deploying the spell you are working on.

**Comment by asymmetric** [comment]
Right, makes sense. I was going to write the spell and then got carried away by trying `seth` and forgot about it :sweat_smile:

**Comment by gbalabasquer** [comment]
It would be interesting the spell accepts array with `ilks` and `lines`. So we make this spell totally flexible and you can choose in the config files to which collaterals apply it.

**Comment by asymmetric** [comment]
Do you see this spell as being used for actual debt ceiling raising, or just as part of the deployment scripts?

I'm wondering if it will happen often in real scenarios that we'll raise the `line` on multiple contracts, and therefore if it makes sense for it to accept an array instead of a single `ilk`.

**Comment by gbalabasquer** [comment]
I think we can prepare both :)

**Pull request merged**
