### PR TITLE
shell.nix

### PR DESCRIPTION
**Pull request by asymmetric**
Easier setup when using nix.

@nanexcool could you test that it uses cachix?

### CODE REVIEW

**Comment by xwvvvvwx** [comment]
this builds solidity from source on my machine. Is that because I don't have the dapphub cachix configured?

**Comment by asymmetric** [comment]
Yep, you need the `dapp` cachix configured, I should add that to the README.

**Comment by xwvvvvwx** [comment]
Is the build error expected?

**Comment by asymmetric** [comment]
BTW I don't have either of those hashes in my store (the hevm and the dapp one).

**Comment by asymmetric** [comment]
@xwvvvvwx could you try again?

**Comment by gbalabasquer** [comment]
sorry about my lack of knowledge about nix, but why do we need all of this here? what is the purpose of adding these files?

**Comment by asymmetric** [comment]
Basically, it defines all dependencies for you, and also sets all the environment variables to their default values, so that you only have to run `nix-shell --argstr eth_from $ETH_FROM`.

This also makes things more reproducible (all dependencies are pinned to a specific version).

**Comment by xwvvvvwx** [comment]
This builds all the way through for me now.

**Comment by asymmetric** [comment]
Lol, so still no cachix? :)

**Comment by xwvvvvwx** [comment]
I still didn't get round to setting it up.

**Pull request merged**
